# -*- coding: utf-8 -*-
"""Python_basico2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jr7hjL0dsjkKGhfQoMyxdorzW_duMp5A

# Atividade 1
"""

x=4
x1=9
x2=5

result1=(((2+5)*3)+x+5)<x1
result2=(((2+5)*3)+(x+5+x1)==(x==6+x2*2))
result3=(((3*6)+x-3)<x2)
result4=(((7*8)>(x+4-x1)<(x*2+x2*9)))

print(f'Resultado 1:{result1}')
print(f'Resultado 1:{result2}')
print(f'Resultado 1:{result3}')
print(f'Resultado 1:{result4}')



"""# Atividade 2"""

n=25
result=(n<=20 or n>=30)
#print(result)
print(f'Esta fora do intervalo: {result}')

n=25
result=(20 < n < 30)
print(f'Esta no intervalo: {result}')

a=20
b=5
result=(a>10 and b<=5)
print(f'Atende as condições: {result}')

a=0
b=4
result=(a>=10 or b<5)
print(f'Atende as condições: {result}')

"""# Atividade Psdeudocodigo - Python

"""

nota1 = 7
nota2 = 7
if(nota1 + nota2) / 2 >= 7:
    print("ALUNO APROVADO")
else:
    print("ALUNO REPROVADO")

#Escreva:nota; media; real
#Digite nota 1
#Digite nota 2
#Leia nota 1 e 2
#Calcule (nota1+nota2)/2
#Se(nota1+nota2)/2)>=7 entao:
#     Imprima "ALUNO APROVADO"
#SENAO
#     imprima "ALUNO REPROVADO"